#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin

mount -t sysfs none /sys
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t configfs none /sys/kernel/config

# disable turn off display
echo -e "\033[9;0]" > /dev/tty0

#Check if there is udc available
DIRECTORY=/sys/class/udc
if [ "ls -A $DIRECTORY" = "" ]; then
echo "No udc available!"
exit 1
fi

# USB UTP setup
mkdir /sys/kernel/config/usb_gadget/g1
cd /sys/kernel/config/usb_gadget/g1/
echo 0x066F > idVendor
echo 0x37FF > idProduct
mkdir strings/0x409

if [ -e /sys/devices/soc0/soc_uid ]
then
cat /sys/devices/soc0/soc_uid > strings/0x409/serialnumber
else
echo 0000000000000000 > strings/0x409/serialnumber
fi

echo Freescale > strings/0x409/manufacturer
echo "FSL i.MX Board" > strings/0x409/product
mkdir configs/c.1
echo 5 > configs/c.1/MaxPower
mkdir functions/mass_storage.1
ln -s functions/mass_storage.1 configs/c.1/
echo /fat > functions/mass_storage.1/lun.0/file

for udc_name in $(ls $DIRECTORY)
do
echo "MFG tool will use 1st udc:$udc_name"
echo $udc_name > UDC
break
done

cd /home

echo "Starting UTP"
uuc
